### ISSUE TITLE
Hybrid Cache - Several instances conflicts

### ISSUE THREAD

**Issue by Valtarr** [imazen/imageflow-server#99]
Hi, I am deploying imageflow server (started from dotnet API with HybridCache enabled) and using the same folder on shared disk (Azure) for all instances (to have shared cached binary files).

But often I have conflicts when several instances are started. Or even when single instance is redeployed (because it is starting another instance first before dropping existing).

Is it expected behavior, or I am doing something wrong with configuration?

Errors look like:

```
[13:24:55 ERR] Failed to open log file /App/cache/hybrid/db/3/00006537939027752052.metastore for reading in shard 3. Perhaps another process is still writing to the log?
System.IO.FileNotFoundException: Could not find file '/App/cache/hybrid/db/3/00006537939027752052.metastore'.
File name: '/App/cache/hybrid/db/3/00006537939027752052.metastore'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at Imazen.HybridCache.MetaStore.WriteLog.Startup()
```

**Comment by lilith** [comment]
This is like putting a postgres database file on a shared network drive and
running multiple servers trying to access it; it's going to fail badly. Per
the docs, it's essential to only use local storage.

**Comment by Valtarr** [comment]
Thanks. Actually, single instance works very well. But not scalable. Will find other solution.
